document.addEventListener("DOMContentLoaded",function(){setTimeout(()=>{document.querySelector('body').style.overflow='unset';document.getElementById('loading').classList.add('loaderMoveUp');document.getElementById('loading').style.display='none';updateStatus()},750);var galery=document.getElementById("galery");var scrollBar=document.getElementById("scrollBar");var scrollIndicator=document.getElementById("scrollIndicator");var startTranslateX=0;var isDragging=false;function handleMove(startX,startTranslateX,clientX){var deltaX=clientX-startX;var percentage=deltaX/(scrollBar.clientWidth-scrollIndicator.clientWidth);var newTranslateX=startTranslateX+percentage*(galery.scrollWidth-galery.clientWidth);newTranslateX=Math.max(0,Math.min(newTranslateX,galery.scrollWidth-galery.clientWidth));if(newTranslateX>=0&&newTranslateX<=galery.scrollWidth-galery.clientWidth){setTranslateX(galery,-newTranslateX);addActiveClassToClosestLi();}
updateScrollIndicatorPosition();}
function onTouchStart(e){e.preventDefault();var touch=e.touches[0];var startX=touch.clientX;startTranslateX=-getTranslateX(galery);function onTouchMove(e){e.preventDefault();var touch=e.touches[0];handleMove(startX,startTranslateX,touch.clientX);}
function onTouchEnd(){setClosestLiCentered();document.removeEventListener("touchmove",onTouchMove);document.removeEventListener("touchend",onTouchEnd);}
document.addEventListener("touchmove",onTouchMove);document.addEventListener("touchend",onTouchEnd);}
function onMouseDown(e){e.preventDefault();isDragging=true;var startX=e.clientX;startTranslateX=-getTranslateX(galery);function onMouseMove(e){if(isDragging){handleMove(startX,startTranslateX,e.clientX);}}
function onMouseUp(){isDragging=false;setClosestLiCentered();document.removeEventListener("mousemove",onMouseMove);document.removeEventListener("mouseup",onMouseUp);}
document.addEventListener("mousemove",onMouseMove);document.addEventListener("mouseup",onMouseUp);}
function onClick(e){if(isDragging){return;}
var clickX=e.clientX-scrollBar.getBoundingClientRect().left;var clickPercentage=clickX/scrollBar.clientWidth;var newTranslateX=clickPercentage*(galery.scrollWidth-galery.clientWidth);newTranslateX=Math.max(0,Math.min(newTranslateX,galery.scrollWidth-galery.clientWidth));setTranslateX(galery,-newTranslateX);addActiveClassToClosestLi();updateScrollIndicatorPosition();setClosestLiCentered();}
function onScrollIndicatorMouseDown(e){e.preventDefault();isDragging=true;var startX=e.clientX;startTranslateX=-getTranslateX(galery);function onMouseMove(e){if(isDragging){handleMove(startX,startTranslateX,e.clientX);}}
function onMouseUp(){isDragging=false;setClosestLiCentered();document.removeEventListener("mousemove",onMouseMove);document.removeEventListener("mouseup",onMouseUp);}
document.addEventListener("mousemove",onMouseMove);document.addEventListener("mouseup",onMouseUp);}
scrollIndicator.addEventListener("touchstart",onTouchStart);scrollIndicator.addEventListener("mousedown",onScrollIndicatorMouseDown);galery.addEventListener("touchstart",onTouchStart);galery.addEventListener("mousedown",onScrollIndicatorMouseDown);scrollBar.addEventListener("click",onClick);function updateScrollIndicatorPosition(){var scrollPercentage=(-getTranslateX(galery)/(galery.scrollWidth-galery.clientWidth))*100;var indicatorPosition=(scrollBar.clientWidth-scrollIndicator.clientWidth)*(scrollPercentage/100);scrollIndicator.style.transform="translate3d("+indicatorPosition+"px, 0, 0)";}
function getTranslateX(element){var transform=window.getComputedStyle(element).getPropertyValue("transform");var match=transform.match(/matrix\(([^\)]+)\)/);if(match){var values=match[1].split(", ");return parseFloat(values[4])||0;}
return 0;}
function setTranslateX(element,value){element.style.transform="translate3d("+value+"px, 0, 0)";}
function addActiveClassToClosestLi(){var elements=galery.getElementsByTagName("li");var closestElementIndex=findClosestElement(galery.clientWidth/2,elements);for(var i=0;i<elements.length;i++){elements[i].classList.remove("active");}
if(closestElementIndex>=0&&closestElementIndex<elements.length){elements[closestElementIndex].classList.add("active");}}
function setClosestLiCentered(element){var elements=galery.getElementsByTagName("li");var closestElementIndex=element||findClosestElement(galery.clientWidth/2,elements);if(closestElementIndex>=0&&closestElementIndex<elements.length){var li=elements[closestElementIndex];var leftSpace=li.offsetLeft;var rightSpace=galery.clientWidth-(leftSpace+li.clientWidth);var centeredTranslateX=galery.scrollLeft+leftSpace-(galery.clientWidth-li.clientWidth)/2;centeredTranslateX=Math.max(0,Math.min(centeredTranslateX,galery.scrollWidth-galery.clientWidth));setTranslateX(galery,-centeredTranslateX);}}
function findClosestElement(position,elements){var closestIndex=0;var closestDistance=Math.abs(position-elements[0].getBoundingClientRect().left);for(var i=1;i<elements.length;i++){var distance=Math.abs(position-elements[i].getBoundingClientRect().left);if(distance<closestDistance){closestIndex=i;closestDistance=distance;}}
return closestIndex;}
galery.getElementsByTagName("li")[1].classList.add('active');setClosestLiCentered(1);updateScrollIndicatorPosition();});